# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('attacker_ip', models.CharField(max_length=100)),
                ('attacker_latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('attacker_longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('attacker_location', models.CharField(max_length=100)),
                ('target_latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('target_longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('target_location', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('port', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
        ),
    ]
