# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberAttack',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('attacker_ip', models.CharField(max_length=100)),
                ('attacker_latitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('attacker_longitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('attacker_location', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('attacker_port', models.DecimalField(decimal_places=0, max_digits=15)),
                ('target_port', models.DecimalField(decimal_places=0, max_digits=15)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_ip', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('target_latitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('target_longitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('target_location', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['target_ip'],
            },
        ),
        migrations.AddField(
            model_name='cyberattack',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyberattackapp.Target'),
        ),
    ]
