# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyberattackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['ip']},
        ),
        migrations.RenameField(
            model_name='target',
            old_name='target_ip',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='target_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='target_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='target_longitude',
            new_name='longitude',
        ),
    ]
